language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
script:
  - nosetests -sv --with-coverage --cover-package=cctvbuffer
after_success:
  - coveralls
